---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: ONTAP tools for VMware vSphere 배포하기 전에 배포 패키지의 공간 요구 사항과 몇 가지 기본 호스트 시스템 요구 사항을 숙지해야 합니다. 
---
= ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 배포하기 전에 배포 패키지의 공간 요구 사항과 몇 가지 기본 호스트 시스템 요구 사항을 숙지해야 합니다.

VMware vCenter Server Virtual Appliance(vCSA)와 함께 ONTAP tools for VMware vSphere 사용할 수 있습니다.  ESXi 시스템을 포함하는 지원되는 vSphere 클라이언트에 ONTAP tools for VMware vSphere 배포해야 합니다.



== 시스템 요구 사항

* *노드당 설치 패키지 공간 요구 사항*
+
** 씬 프로비저닝 설치의 경우 15GB
** 두꺼운 프로비저닝 설치의 경우 348GB


* *호스트 시스템 크기 요구 사항* 배포 크기에 따른 권장 메모리는 아래 표와 같습니다.  고가용성(HA)을 구축하려면 표에 명시된 어플라이언스 크기의 3배가 필요합니다.


|===


| *배치 유형* | *노드당 CPU* | *노드당 메모리(GB)* | *노드당 두꺼운 프로비저닝 디스크 공간(GB)* 


| 작은 | 9 | 18 | 350 


| 중간 | 13 | 26 | 350 


| 대규모 참고: 대규모 배포는 HA 구성에만 적용됩니다. | 17 | 34 | 350 
|===

NOTE: 백업이 활성화되면 각 ONTAP 도구 클러스터에는 VM이 ​​배포된 데이터 저장소에 50GB의 추가 공간이 필요합니다.  따라서 non-HA는 400GB가 필요하고, HA는 총 1100GB의 공간이 필요합니다.



== 최소 저장 및 적용 요구 사항

|===
| 저장소, 호스트 및 애플리케이션 | 버전 요구 사항 


| ONTAP | 9.14.1, 9.15.1, 9.16.0, 9.16.1 및 9.16.1P3 FAS, ASA A-시리즈, ASA C-시리즈, AFF A-시리즈, AFF C-시리즈 및 ASA r2. 


| ONTAP 도구는 ESXi 호스트를 지원합니다. | 7.0.3부터 


| ONTAP 도구 지원 vCenter Server | 7.0U3 이상 


| VASA 제공자 | 3.0 


| OVA 애플리케이션 | 10.4 


| ONTAP 도구 가상 머신을 배포하기 위한 ESXi 호스트 | 7.0U3 및 8.0U3 


| ONTAP 도구 가상 머신을 배포하기 위한 vCenter Server | 7.0과 8.0 
|===

NOTE: ONTAP tools for VMware vSphere 부터 가상 머신 하드웨어가 버전 10에서 17로 변경되었습니다.

상호 운용성 매트릭스 도구(IMT)에는 지원되는 ONTAP, vCenter Server, ESXi 호스트 및 플러그인 애플리케이션 버전에 대한 최신 정보가 포함되어 있습니다.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["상호 운용성 매트릭스 도구"^]



== 포트 요구 사항

다음 표는 NetApp 에서 사용하는 네트워크 포트와 그 용도를 간략하게 설명합니다. 포트에는 세 가지 유형이 있습니다.

* 외부 포트: 이 포트는 Kubernetes 클러스터나 노드 외부에서 접근할 수 있습니다.  이를 통해 서비스가 외부 네트워크나 사용자와 통신할 수 있으므로 클러스터 환경 외부의 시스템과 통합이 가능합니다.
* 노드 간 포트: 이 포트는 Kubernetes 클러스터 내의 노드 간 통신을 가능하게 합니다.  데이터 공유나 협력과 같은 클러스터 작업에 필요합니다.  단일 노드 배포의 경우 노드 간 포트는 노드 내부에서만 사용되며 외부 액세스가 필요하지 않습니다.  노드 간 포트는 클러스터 외부에서 트래픽을 허용할 수 있습니다.  방화벽 규칙을 사용하여 인터넷 접근에서 노드 간 포트를 차단합니다.
* 내부 포트: 이 포트는 ClusterIP 주소를 사용하여 Kubernetes 클러스터 내에서 통신합니다.  이러한 항목은 외부에 노출되지 않으며 방화벽 규칙에 추가할 필요가 없습니다.



NOTE: 모든 ONTAP 도구 노드가 동일한 서브넷에 상주하여 서로 중단 없는 통신을 유지하도록 합니다.


|===
| *서비스/구성요소 이름* | *포트* | *규약* | *포트 유형* | *설명* 


| ntv-게이트웨이-서비스(LB) | 443, 8443 | TCP | 외부 | VASA 공급자 서비스에 대한 수신 통신을 위한 통과 포트입니다. VASA 공급자 자체 서명 인증서와 사용자 정의 CA 인증서가 이 포트에 호스팅됩니다. 


| SSH | 22 | TCP | 외부 | 원격 서버 로그인 및 명령 실행을 위한 Secure Shell입니다. 


| rke2 서버 | 9345 | TCP | 노드 간 | RKE2 감독자 API(신뢰할 수 있는 네트워크로 제한). 


| kube-apiserver | 6443 | TCP | 노드 간 | Kubernetes API 서버 포트(신뢰할 수 있는 네트워크로 제한). 


| rpcbind/포트매퍼 | 111 | TCP/UDP | 노드 간 | 서비스 간 RPC 통신에 사용됩니다. 


| 코어드ns(DNS) | 53 | TCP/UDP | 노드 간 | 클러스터 내에서 이름 확인을 위한 도메인 이름 시스템(DNS) 서비스입니다. 


| 엔티피 | 123 | UDP | 노드 간 | 시간 동기화를 위한 네트워크 시간 프로토콜(NTP) 


| 등 | 2379, 2380, 2381 | TCP | 노드 간 | 클러스터 데이터의 키-값 저장소입니다. 


| 큐브-vip | 2112 | TCP | 노드 간 | Kubernetes API 서버 포트. 


| 쿠벨렛 | 10248, 10250 | TCP | 노드 간 | 쿠버네티스 구성 요소 


| kube-controller | 10257 | TCP | 노드 간 | 쿠버네티스 구성 요소 


| 클라우드 컨트롤러 | 10258 | TCP | 노드 간 | 쿠버네티스 구성 요소 


| kube-scheduler | 10259 | TCP | 노드 간 | 쿠버네티스 구성 요소 


| kube-proxy | 10249, 10256 | TCP | 노드 간 | 쿠버네티스 구성 요소 


| 캘리코 마디 | 9091, 9099 | TCP | 노드 간 | Calico 네트워킹 구성 요소. 


| 컨테이너 | 10010 | TCP | 노드 간 | 컨테이너 데몬 서비스. 


| VXLAN(플란넬) | 8472 | UDP | 노드 간 | 포드 통신을 위한 오버레이 네트워크. 
|===

NOTE: HA 배포의 경우 모든 노드 간에 UDP 포트 8472가 열려 있는지 확인하세요.  이 포트는 노드 간 포드 간 통신을 가능하게 하며, 이를 차단하면 노드 간 네트워킹이 중단됩니다.



== ONTAP tools for VMware vSphere 배포를 위한 구성 제한

다음 표를 가이드로 사용하여 ONTAP tools for VMware vSphere 구성할 수 있습니다.

|===


| *전개* | *유형* | * vVols 수 * | *호스트 수* 


| 비HA | 소형(S) | ~12K | 32 


| 비HA | 중간(M) | ~24K | 64 


| 고가용성 | 소형(S) | ~24K | 64 


| 고가용성 | 중간(M) | ~5만 | 128 


| 고가용성 | 대형(L) | ~10만 | 256 [참고] 표의 호스트 수는 여러 vCenter의 총 호스트 수를 보여줍니다. 
|===


== ONTAP tools for VMware vSphere - 스토리지 복제 어댑터(SRA)

다음 표는 ONTAP tools for VMware vSphere 사용하여 VMware Live Site Recovery 인스턴스당 지원되는 숫자를 보여줍니다.

|===
| *vCenter 배포 크기* | *작은* | *중간* 


| 어레이 기반 복제를 사용하여 보호를 위해 구성된 총 가상 머신 수 | 2000 | 5000 


| 어레이 기반 복제 보호 그룹의 총 수 | 250 | 250 


| 복구 계획당 보호 그룹의 총 수 | 50 | 50 


| 복제된 데이터 저장소 수 | 255 | 255 


| VM 수 | 4000 | 7000 
|===
다음 표는 ONTAP tools for VMware vSphere 보여줍니다.

|===


| *VMware Live Site Recovery 인스턴스 수* | * ONTAP 도구 배포 크기* 


| 최대 4개 | 작은 


| 4에서 8까지 | 중간 


| 8개 이상 | 크기가 큰 
|===
자세한 내용은 다음을 참조하세요.  https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["VMware Live Site Recovery의 운영 한계"] .
