---
permalink: protect/configure-on-srm-appliance.html 
sidebar: sidebar 
keywords:  
summary: 'VMware Live Site Recovery 어플라이언스를 배포한 후 재해 복구 관리를 활성화하기 위해 SRA(스토리지 복제 어댑터)를 구성합니다.' 
---
= VMware Live Site Recovery 어플라이언스에서 SRA 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware Live Site Recovery 어플라이언스를 배포한 후 재해 복구 관리를 활성화하기 위해 SRA(스토리지 복제 어댑터)를 구성합니다.

VMware Live Site Recovery 어플라이언스에서 SRA를 구성하면 어플라이언스 내에 ONTAP tools for VMware vSphere 저장되어 VMware Live Site Recovery와 SRA 간의 통신이 가능해집니다.

.시작하기 전에
* _.tar.gz_ 파일을 다운로드하세요. https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab["NetApp 지원 사이트"] .
* ONTAP 도구 관리자에서 SRA 서비스를 활성화합니다. 자세한 내용은 link:../manage/enable-services.html["서비스 활성화"] 부분.
* VMware vSphere 어플라이언스용 ONTATP 도구에 vCenter Server를 추가합니다. 자세한 내용은 link:../configure/add-vcenter.html["vCenter 서버 추가"] 부분.
* ONTAP tools for VMware vSphere 에 스토리지 백엔드를 추가합니다. 자세한 내용은 link:../configure/add-storage-backend.html["스토리지 백엔드 추가"] 부분.


.단계
. VMware Live Site Recovery 어플라이언스 화면에서 *스토리지 복제 어댑터* > *새 어댑터*를 선택합니다.
. _.tar.gz_ 파일을 VMware Live Site Recovery에 업로드합니다.
. PuTTY와 같은 SSH 클라이언트를 통해 관리자 계정으로 VMware Live Site Recovery 어플라이언스에 로그인합니다.
. 다음 명령을 사용하여 루트 사용자로 전환합니다. `su root`
. 명령을 실행하세요 `cd /var/log/vmware/srm` 로그 디렉토리로 이동합니다.
. 로그 위치에서 다음 명령을 입력하여 SRA에서 사용하는 Docker ID를 가져옵니다. `docker ps -l`
. 컨테이너 ID에 로그인하려면 다음 명령을 입력하세요. `docker exec -it -u srm <container id> sh`
. 다음 명령을 사용하여 ONTAP tools for VMware vSphere IP 주소와 비밀번호를 사용하여 VMware Live Site Recovery를 구성합니다.  `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <Application username> --otv-password <Application password> --vcenter-guid <VCENTER_GUID>`
+
** 비밀번호를 작은따옴표로 묶어 제공하면 Perl 스크립트가 특수문자를 구분 기호가 아닌 비밀번호의 일부로 처리합니다.
** ONTAP 도구 관리자에서 애플리케이션(VASA Provider/SRA) 사용자 이름과 비밀번호를 설정할 수 있습니다. 이 자격 증명을 사용하여 SRA를 VMware Live Site Recovery에 등록합니다.
** vCenter GUID를 찾으려면 vCenter 인스턴스를 추가한 후 ONTAP 도구 관리자의 vCenter Server 페이지로 이동합니다. 참조하다link:../configure/add-vcenter.html["vCenter 서버 추가"] 부분.


. 어댑터를 다시 검사하여 업데이트된 세부 정보가 VMware Live Site Recovery Storage Replication 어댑터 페이지에 나타나는지 확인합니다.


.결과
저장소 자격 증명이 저장되었음을 나타내는 확인 메시지가 나타납니다. 이제 SRA는 지정된 IP 주소, 포트 및 자격 증명을 사용하여 SRA 서버와 통신할 수 있습니다.
