---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 보호된 사이트의 가상 머신 그룹을 보호하려면 보호 그룹을 만들어야 합니다. 
---
= 보호 및 복구 사이트 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보호된 사이트의 가상 머신 그룹을 보호하려면 보호 그룹을 만들어야 합니다.

새 데이터스토어를 추가할 때 기존 데이터스토어 그룹에 포함하거나, 새 데이터스토어를 추가하고 보호를 위한 새 볼륨 또는 일관성 그룹을 생성할 수 있습니다. 보호된 일관성 그룹 또는 볼륨에 새 데이터스토어를 추가한 후에는 SnapMirror 업데이트하고 보호 사이트와 복구 사이트 모두에서 스토리지 검색을 수행합니다. 새 데이터스토어가 감지되고 보호되도록 검색을 수동으로 또는 일정에 따라 실행할 수 있습니다.



== 보호 사이트와 복구 사이트 쌍

vSphere Client를 사용하여 만든 보호 사이트와 복구 사이트를 페어링하여 SRA(스토리지 복제 어댑터)가 스토리지 시스템을 검색할 수 있도록 해야 합니다.


NOTE: SRA(스토리지 복제 어댑터)는 일관성 그룹의 자동 장애 조치 이중화 유형의 동기화 관계 하나와 SnapMirror 비동기 관계를 통한 팬아웃을 지원합니다.  그러나 일관성 그룹에 두 개의 비동기 SnapMirror 있는 팬아웃이나 볼륨에 있는 팬아웃 SnapMirror는 지원되지 않습니다.

.시작하기 전에
* 보호된 사이트와 복구 사이트에 VMware Live Site Recovery를 설치해야 합니다.
* 보호 사이트와 복구 사이트에 SRA를 설치해야 합니다.


.단계
. vSphere Client 홈페이지에서 *사이트 복구*를 두 번 클릭하고 *사이트*를 선택합니다.
. *개체* > *작업* > *사이트 쌍*을 선택합니다.
. *사이트 복구 관리자 서버 페어링* 대화 상자에서 보호된 사이트의 Platform Services Controller 주소를 입력한 후 *다음*을 선택합니다.
. vCenter Server 선택 섹션에서 다음을 수행합니다.
+
.. 보호된 사이트의 vCenter Server가 페어링할 수 있는 일치 후보로 나타나는지 확인합니다.
.. SSO 관리 자격 증명을 입력한 다음 *마침*을 선택합니다.


. 메시지가 표시되면 *예*를 선택하여 보안 인증서를 수락합니다.


.결과
보호된 사이트와 복구 사이트 모두 개체 대화 상자에 나타납니다.



== 보호 그룹 구성

.시작하기 전에
소스 사이트와 대상 사이트 모두 다음 사항에 대해 구성되어 있는지 확인해야 합니다.

* 동일한 버전의 VMware Live Site Recovery가 설치됨
* 가상 머신
* 보호 및 복구 사이트 페어링
* 소스 및 대상 데이터 저장소는 각 사이트에 마운트되어야 합니다.


.단계
. vCenter Server에 로그인하고 *사이트 복구* > *보호 그룹*을 선택합니다.
. *보호 그룹* 창에서 *새로 만들기*를 선택합니다.
. 보호 그룹에 대한 이름과 설명, 방향을 지정하고 *다음*을 선택합니다.
. *유형* 필드에서 NFS 및 VMFS 데이터 저장소에 대한 데이터 저장소 그룹(배열 기반 복제)으로 *유형 필드 옵션...*을 선택합니다. 장애 도메인은 복제가 활성화된 SVM뿐입니다. 피어링만 구현되어 있고 문제가 없는 SVM이 표시됩니다.
. 복제 그룹 탭에서 활성화된 어레이 쌍이나 구성한 가상 머신이 있는 복제 그룹을 선택한 후 *다음*을 선택합니다.
+
복제 그룹의 모든 가상 머신이 보호 그룹에 추가됩니다.

. 기존 복구 계획을 선택하거나 *새 복구 계획에 추가*를 선택하여 새 복구 계획을 만들 수 있습니다.
. 완료 준비 탭에서 생성한 보호 그룹의 세부 정보를 검토한 다음 *마침*을 선택합니다.

