---
permalink: concepts/rbac-ontap-use.html 
sidebar: sidebar 
keywords: ontap rbac, use ontap rbac 
summary: ONTAP 사용하여 ONTAP tools for VMware vSphere 에는 프로덕션 환경에서 사용하기 전에 고려해야 할 여러 가지 측면이 있습니다. 
---
= ONTAP tools for VMware vSphere 와 함께 ONTAP RBAC 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 사용하여 ONTAP tools for VMware vSphere 에는 프로덕션 환경에서 사용하기 전에 고려해야 할 여러 가지 측면이 있습니다.



== 구성 프로세스 개요

ONTAP tools for VMware vSphere 사용자 정의 역할이 있는 ONTAP 사용자를 만드는 기능이 포함되어 있습니다. 정의는 ONTAP 클러스터에 업로드할 수 있는 JSON 파일에 패키징됩니다. 사용자를 만들고 해당 환경과 보안 요구 사항에 맞게 역할을 조정할 수 있습니다.

주요 구성 단계는 아래에 자세히 설명되어 있습니다.  참조하다link:../configure/configure-user-role-and-privileges.html["ONTAP 사용자 역할 및 권한 구성"] 자세한 내용은.

.1. 준비하다
ONTAP 도구 관리자와 ONTAP 클러스터 모두에 대한 관리 자격 증명이 필요합니다.

.2. JSON 정의 파일을 다운로드하세요
ONTAP 도구 관리자 사용자 인터페이스에 로그인하면 RBAC 정의가 포함된 JSON 파일을 다운로드할 수 있습니다.

.3. 역할이 있는 ONTAP 사용자 생성
시스템 관리자에 로그인한 후 사용자와 역할을 생성할 수 있습니다.

. 왼쪽에서 *클러스터*를 선택한 다음 *설정*을 선택합니다.
. *사용자 및 역할*까지 아래로 스크롤하여 클릭하세요. `-->` .
. *사용자*에서 *추가*를 선택하고 *가상화 제품*을 선택합니다.
. 로컬 워크스테이션에서 JSON 파일을 선택하여 업로드합니다.


.4. 역할 구성
역할을 정의하는 과정에서 몇 가지 관리적 결정을 내려야 합니다.  보다<<시스템 관리자를 사용하여 역할 구성>> 자세한 내용은.



== 시스템 관리자를 사용하여 역할 구성

System Manager에서 새로운 사용자와 역할을 만들고 JSON 파일을 업로드한 후에는 환경과 요구 사항에 맞게 역할을 사용자 정의할 수 있습니다.



=== 핵심 사용자 및 역할 구성

RBAC 정의는 VSC, VASA Provider, SRA의 조합을 포함한 여러 제품 기능으로 패키지화되어 있습니다.  RBAC 지원이 필요한 환경을 선택해야 합니다.  예를 들어, 원격 플러그인 기능을 지원하는 역할을 원하는 경우 VSC를 선택합니다.  또한 사용자 이름과 관련 비밀번호를 선택해야 합니다.



=== Privileges

역할 권한은 ONTAP 저장소에 필요한 액세스 수준에 따라 4개 세트로 구성됩니다.  역할의 기반이 되는 권한은 다음과 같습니다.

* 발견
+
이 역할을 사용하면 스토리지 시스템을 추가할 수 있습니다.

* 저장소 만들기
+
이 역할을 통해 저장소를 만들 수 있습니다.  여기에는 검색 역할과 관련된 모든 권한도 포함됩니다.

* 저장소 수정
+
이 역할을 사용하면 저장소를 수정할 수 있습니다.  여기에는 검색 및 저장소 역할 생성과 관련된 모든 권한도 포함됩니다.

* 저장소 파괴
+
이 역할을 사용하면 저장소를 파괴할 수 있습니다.  여기에는 검색, 저장소 생성, 저장소 역할 수정과 관련된 모든 권한이 포함됩니다.





=== 역할이 있는 사용자 생성

환경에 대한 구성 옵션을 선택한 후 *추가*를 클릭하면 ONTAP 에서 사용자와 역할을 생성합니다.  생성된 역할의 이름은 다음 값을 연결한 것입니다.

* JSON 파일에 정의된 상수 접두사 값(예: "OTV_10")
* 선택한 제품 기능
* 권한 집합 목록입니다.


.예
`OTV_10_VSC_Discovery_Create`

새로운 사용자는 "사용자 및 역할" 페이지의 목록에 추가됩니다.  HTTP와 ONTAPI 사용자 로그인 방법이 모두 지원됩니다.
