---
permalink: concepts/rbac-learn-about.html 
sidebar: sidebar 
keywords: role based access control, rbac, rbac components, learn about rbac 
summary: '역할 기반 접근 제어(RBAC)는 조직 내 리소스에 대한 접근을 제어하기 위한 보안 프레임워크입니다.  RBAC는 개별 사용자에게 권한을 할당하는 대신, 작업을 수행하기 위한 특정 수준의 권한을 가진 역할을 정의하여 관리를 간소화합니다.  정의된 역할은 사용자에게 할당되므로 오류 위험을 줄이고 조직 전체의 액세스 제어 관리를 간소화하는 데 도움이 됩니다.' 
---
= ONTAP tools for VMware vSphere 에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
역할 기반 접근 제어(RBAC)는 조직 내 리소스에 대한 접근을 제어하기 위한 보안 프레임워크입니다.  RBAC는 개별 사용자에게 권한을 할당하는 대신, 작업을 수행하기 위한 특정 수준의 권한을 가진 역할을 정의하여 관리를 간소화합니다.  정의된 역할은 사용자에게 할당되므로 오류 위험을 줄이고 조직 전체의 액세스 제어 관리를 간소화하는 데 도움이 됩니다.

RBAC 표준 모델은 점점 더 복잡해지는 여러 구현 기술 또는 단계로 구성됩니다.  결과적으로 실제 RBAC 배포는 소프트웨어 공급업체와 고객의 요구 사항에 따라 다를 수 있으며 비교적 간단한 것부터 매우 복잡한 것까지 다양합니다.



== RBAC 구성 요소

높은 수준에서 보면, 일반적으로 모든 RBAC 구현에는 여러 가지 구성 요소가 포함됩니다.  이러한 구성 요소는 승인 프로세스를 정의하는 일부로 다양한 방식으로 결합됩니다.

.Privileges
_권한_은 허용되거나 거부될 수 있는 동작이나 기능입니다. 파일을 읽을 수 있는 권한처럼 간단한 것일 수도 있고, 특정 소프트웨어 시스템에 특화된 보다 추상적인 작업일 수도 있습니다. REST API 엔드포인트 및 CLI 명령에 대한 액세스를 제한하기 위해 Privileges 정의할 수도 있습니다. 모든 RBAC 구현에는 미리 정의된 권한이 포함되어 있으며, 관리자가 사용자 지정 권한을 생성할 수도 있습니다.

.역할
_역할_은 하나 이상의 권한을 포함하는 컨테이너입니다.  역할은 일반적으로 특정 업무나 직무 기능에 따라 정의됩니다.  역할이 사용자에게 할당되면 해당 역할에 포함된 모든 권한이 사용자에게 부여됩니다.  권한과 마찬가지로 구현에는 미리 정의된 역할이 포함되며 일반적으로 사용자 정의 역할을 만들 수 있습니다.

.사물
_객체_는 RBAC 환경 내에서 식별된 실제 또는 추상적인 리소스를 나타냅니다.  권한을 통해 정의된 작업은 연관된 개체에서 수행됩니다.  구현에 따라 권한은 객체 유형이나 특정 객체 인스턴스에 부여될 수 있습니다.

.사용자 및 그룹
_사용자_는 인증 후 적용되는 역할에 할당되거나 연결됩니다.  일부 RBAC 구현에서는 사용자에게 하나의 역할만 할당하는 것을 허용하는 반면, 다른 구현에서는 사용자당 여러 역할을 허용하며, 한 번에 하나의 역할만 활성화될 수도 있습니다.  _그룹_에 역할을 할당하면 보안 관리가 더욱 간소화될 수 있습니다.

.권한
_권한_은 역할과 함께 사용자 또는 그룹을 개체에 연결하는 정의입니다.  권한은 계층적 개체 모델에서 유용할 수 있으며, 이 경우 권한은 계층 구조의 자식에게 선택적으로 상속될 수 있습니다.



== 두 가지 RBAC 환경

ONTAP tools for VMware vSphere 사용할 때 고려해야 할 두 가지 RBAC 환경이 있습니다.

.VMware vCenter Server
VMware vCenter Server의 RBAC 구현은 vSphere Client 사용자 인터페이스를 통해 노출된 개체에 대한 액세스를 제한하는 데 사용됩니다.  ONTAP tools for VMware vSphere 설치하는 과정에서 RBAC 환경이 확장되어 ONTAP 도구의 기능을 나타내는 추가 개체가 포함되었습니다.  이러한 객체에 대한 액세스는 원격 플러그인을 통해 제공됩니다.link:../concepts/rbac-vcenter-environment.html["vCenter Server RBAC 환경"] 자세한 내용은.

.ONTAP 클러스터
ONTAP tools for VMware vSphere ONTAP REST API를 통해 ONTAP 클러스터에 연결하여 스토리지 관련 작업을 수행합니다.  저장 리소스에 대한 액세스는 인증 중에 제공된 ONTAP 사용자와 연관된 ONTAP 역할을 통해 제어됩니다. 보다 link:../concepts/rbac-ontap-environment.html["ONTAP RBAC 환경"] 자세한 내용은.
