---
sidebar: sidebar 
permalink: automation/learn-rest-api.html 
keywords: ontap tools vmware vsphere rest api 
summary: ONTAP tools for VMware vSphere 가상 머신 수명 주기 관리를 위한 도구 세트입니다.  여기에는 자동화 프로세스의 일부로 사용할 수 있는 강력한 REST API가 포함되어 있습니다. 
---
= ONTAP tools for VMware vSphere 에 대해 알아보세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 가상 머신 수명 주기 관리를 위한 도구 세트입니다.  여기에는 자동화 프로세스의 일부로 사용할 수 있는 강력한 REST API가 포함되어 있습니다.



== REST 웹 서비스 기반

REST(Representational State Transfer)는 웹 서비스 API 설계를 포함하여 분산 웹 애플리케이션을 만드는 데 사용되는 스타일입니다.  이는 서버 기반 리소스를 노출하고 해당 상태를 관리하기 위한 기술 세트를 확립합니다.

.자원과 국가 대표
리소스는 REST 웹 서비스 애플리케이션의 기본 구성 요소입니다.  REST API를 설계할 때 두 가지 중요한 초기 작업이 있습니다.

* 시스템 또는 서버 기반 리소스 식별
* 리소스 상태 및 연관된 상태 전환 작업을 정의합니다.


클라이언트 애플리케이션은 명확하게 정의된 메시지 흐름을 통해 리소스 상태를 표시하고 변경할 수 있습니다.

.HTTP 메시지
하이퍼텍스트 전송 프로토콜(HTTP)은 웹 서비스 클라이언트와 서버가 리소스에 대한 메시지를 교환하는 데 사용되는 프로토콜입니다.  이는 생성, 읽기, 업데이트, 삭제와 같은 일반적인 작업을 기반으로 하는 CRUD 모델을 따릅니다.  HTTP 프로토콜에는 요청 및 응답 헤더와 응답 상태 코드가 포함됩니다.

.JSON 데이터 포맷
사용 가능한 메시지 형식은 여러 가지가 있지만 가장 인기 있는 옵션은 JSON(JavaScript Object Notation)입니다.  JSON은 일반 텍스트로 간단한 데이터 구조를 표현하기 위한 산업 표준이며, 리소스와 원하는 작업을 설명하는 상태 정보를 전송하는 데 사용됩니다.

.보안
보안은 REST API의 중요한 측면입니다.  ONTAP tools for VMware vSphere 네트워크 상의 HTTP 트래픽을 보호하는 데 사용되는 TLS(전송 계층 보안) 프로토콜 외에도 인증을 위해 액세스 토큰을 사용합니다.  액세스 토큰을 획득하여 후속 API 호출에 사용해야 합니다.

.비동기 요청 지원
ONTAP tools for VMware vSphere 대부분의 요청을 동기적으로 수행하며 작업이 완료되면 상태 코드를 반환합니다.  또한 완료하는 데 오랜 시간이 걸리는 작업에 대해 비동기 처리를 지원합니다.



== ONTAP 도구 관리자 환경

ONTAP 도구 관리자 환경에는 고려해야 할 여러 가지 측면이 있습니다.

.가상 머신
ONTAP tools for VMware vSphere vSphere 원격 플러그인 아키텍처를 사용하여 배포됩니다. REST API 지원을 포함한 소프트웨어는 별도의 가상 머신에서 실행됩니다.

.ONTAP 도구 IP 주소
ONTAP tools for VMware vSphere 가상 머신 기능에 대한 게이트웨이를 제공하는 단일 IP 주소를 제공합니다.  초기 구성 중에 주소를 제공해야 하며 해당 주소는 내부 로드 밸런서 구성 요소에 할당됩니다.  이 주소는 ONTAP 도구 관리자 사용자 인터페이스에서 사용되며 Swagger 문서 페이지와 REST API에 직접 액세스하는 데에도 사용됩니다.

.두 개의 REST API
ONTAP tools for VMware vSphere 외에도 ONTAP 클러스터에는 자체 REST API가 있습니다.  ONTAP 도구 관리자는 ONTAP REST API를 클라이언트로 사용하여 스토리지 관련 작업을 수행합니다.  이 두 API는 별개이고 구별된다는 점을 명심하는 것이 중요합니다. 자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/ontap-automation/["ONTAP 자동화"^] .
