---
permalink: automation/rest-implementation.html 
sidebar: sidebar 
keywords: ontap tools vmware vsphere rest api reference 
summary: REST는 공통적인 기술과 모범 사례를 확립하지만, 각 API의 정확한 구현은 설계 선택에 따라 달라질 수 있습니다.  ONTAP tools for VMware vSphere 사용하기 전에 해당 도구가 어떻게 설계되었는지 숙지해야 합니다. 
---
= ONTAP tools for VMware vSphere 에 대한 구현 세부 정보
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
REST는 공통적인 기술과 모범 사례를 확립하지만, 각 API의 정확한 구현은 설계 선택에 따라 달라질 수 있습니다.  ONTAP tools for VMware vSphere 사용하기 전에 해당 도구가 어떻게 설계되었는지 숙지해야 합니다.

REST API에는 vCenter 및 집계와 같은 여러 리소스 범주가 포함됩니다.  검토하다link:../automation/api-reference.html["API 참조"] 자세한 내용은.



== REST API에 접근하는 방법

포트와 함께 ONTAP 도구 IP 주소를 통해 ONTAP tools for VMware vSphere 액세스할 수 있습니다.  전체 URL에는 다음을 포함한 여러 부분이 있습니다.

* ONTAP 도구 IP 주소 및 포트
* API 버전
* 리소스 카테고리
* 특정 리소스


초기 설정 과정에서 IP 주소를 구성해야 하며, 포트는 8443으로 고정되어 있습니다. URL의 첫 번째 부분은 ONTAP tools for VMware vSphere 에서 일관되며, 엔드포인트 간에 리소스 범주와 특정 리소스만 변경됩니다.


CAUTION: 아래 예시의 IP 주소와 포트 값은 단지 설명 목적으로만 사용됩니다.  사용자 환경에 맞게 이 값을 변경해야 합니다.

.인증 서비스에 액세스하는 예
`\https://10.61.25.34:8443/virtualization/api/v1/auth/login`

이 URL은 POST 메서드를 사용하여 액세스 토큰을 요청하는 데 사용할 수 있습니다.

.vCenter 서버를 나열하는 예
`\https://10.61.25.34:8443/virtualization/api/v1/vcenters`

이 URL은 GET 메서드를 사용하여 정의된 vCenter 서버 인스턴스 목록을 요청하는 데 사용할 수 있습니다.



== HTTP 세부 정보

ONTAP tools for VMware vSphere HTTP 및 관련 매개변수를 사용하여 리소스 인스턴스와 컬렉션에 대해 작업을 수행합니다.  HTTP 구현에 대한 세부 사항은 아래와 같습니다.



=== HTTP 메서드

REST API가 지원하는 HTTP 메서드 또는 동사는 아래 표에 나와 있습니다.

[cols="15,15,70"]
|===
| 방법 | 크러드 | 설명 


| 얻다 | 읽다 | 리소스 인스턴스 또는 컬렉션에 대한 개체 속성을 검색합니다.  이것은 컬렉션과 함께 사용될 경우 목록 작업으로 간주됩니다. 


| 우편 | 만들다 | 입력 매개변수를 기반으로 새로운 리소스 인스턴스를 생성합니다. 


| 놓다 | 업데이트 | 제공된 JSON 요청 본문으로 전체 리소스 인스턴스를 업데이트합니다. 사용자가 수정할 수 없는 키 값은 그대로 유지됩니다. 


| 반점 | 업데이트 | 요청에서 선택한 변경 사항 집합을 리소스 인스턴스에 적용하도록 요청합니다. 


| 삭제 | 삭제 | 기존 리소스 인스턴스를 삭제합니다. 
|===


=== 요청 및 응답 헤더

다음 표는 REST API와 함께 사용되는 가장 중요한 HTTP 헤더를 요약한 것입니다.

[cols="30,15,55"]
|===
| 헤더 | 유형 | 사용 참고 사항 


| 수용하다 | 요구 | 이는 클라이언트 애플리케이션이 수용할 수 있는 콘텐츠 유형입니다.  유효한 값에는 '\*/*` 또는 `application/json` . 


| x-인증 | 요구 | 클라이언트 애플리케이션을 통해 요청을 발행하는 사용자를 식별하는 액세스 토큰이 포함되어 있습니다. 


| 콘텐츠 유형 | 응답 | 서버에서 반환됨 `Accept` 요청 헤더. 
|===


=== HTTP 상태 코드

REST API에서 사용하는 HTTP 상태 코드는 아래와 같습니다.

[cols="15,20,65"]
|===
| 암호 | 의미 | 설명 


| 200 | OK | 새로운 리소스 인스턴스를 생성하지 않는 호출의 경우 성공을 나타냅니다. 


| 201 | 생성됨 | 리소스 인스턴스에 대한 고유 식별자가 있는 개체가 성공적으로 생성되었습니다. 


| 202 | 수락됨 | 요청이 수락되었고 요청을 수행하기 위한 백그라운드 작업이 생성되었습니다. 


| 204 | 내용이 없습니다 | 요청은 성공했지만 콘텐츠가 반환되지 않았습니다. 


| 400 | 잘못된 요청 | 요청 입력이 인식되지 않거나 부적절합니다. 


| 401 | 허가받지 않음 | 사용자에게 권한이 없으므로 인증이 필요합니다. 


| 403 | 금지됨 | 인증 오류로 인해 접근이 거부되었습니다. 


| 404 | 찾을 수 없음 | 요청에 언급된 리소스가 존재하지 않습니다. 


| 409 | 갈등 | 개체가 이미 존재하기 때문에 개체를 생성하려는 시도가 실패했습니다. 


| 500 | 내부 오류 | 서버에서 일반적인 내부 오류가 발생했습니다. 
|===


== 입증

REST API에 대한 클라이언트 인증은 액세스 토큰을 사용하여 수행됩니다.  토큰 및 인증 프로세스의 관련 특징은 다음과 같습니다.

* 클라이언트는 ONTAP 도구 관리자 자격 증명(사용자 이름 및 비밀번호)을 사용하여 토큰을 요청해야 합니다.
* 토큰은 JSON 웹 토큰(JWT) 형식으로 지정됩니다.
* 각 토큰은 60분 후에 만료됩니다.
* 클라이언트의 API 요청에는 토큰이 포함되어야 합니다. `x-auth` 요청 헤더.


참조하다link:../automation/first-call.html["첫 번째 REST API 호출"] 액세스 토큰을 요청하고 사용하는 예를 들어 보겠습니다.



== 동기 및 비동기 요청

대부분의 REST API 호출은 빠르게 완료되므로 동기적으로 실행됩니다.  즉, 요청이 완료된 후 상태 코드(예: 200)를 반환합니다.  완료하는 데 시간이 오래 걸리는 요청은 백그라운드 작업을 사용하여 비동기적으로 실행됩니다.

비동기적으로 실행되는 API 호출을 실행한 후 서버는 202 HTTP 상태 코드를 반환합니다.  이는 요청이 수락되었지만 아직 완료되지 않았음을 나타냅니다.  백그라운드 작업을 쿼리하여 성공 또는 실패 등의 상태를 확인할 수 있습니다.

비동기 처리는 데이터 저장소 및 vVol 작업을 포함한 여러 유형의 장기 실행 작업에 사용됩니다.  자세한 내용은 Swagger 페이지에서 REST API의 작업 관리자 범주를 참조하세요.
