---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 백엔드는 ESXi 호스트가 데이터를 저장하는 데 사용하는 시스템입니다. 
---
= 스토리지 백엔드 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 백엔드를 추가하면 ONTAP 클러스터를 온보딩할 수 있습니다.

*이 작업에 관하여*

vCenter가 연관된 SVM이 있는 테넌트 역할을 하는 다중 테넌시 설정의 경우 ONTAP 도구 관리자를 사용하여 클러스터를 추가합니다.  스토리지 백엔드를 vCenter Server와 연결하여 온보딩된 vCenter Server 인스턴스에 전역적으로 매핑합니다.  vCenter 테넌트는 원하는 스토리지 가상 머신(SVM)을 온보딩해야 합니다.  이를 통해 SVM 사용자는 vVols 데이터 저장소를 프로비저닝할 수 있습니다.  SVM을 사용하여 vCenter에 스토리지를 추가할 수 있습니다.

ONTAP 도구 사용자 인터페이스를 사용하여 클러스터 또는 SVM 자격 증명으로 로컬 스토리지 백엔드를 추가합니다.  이러한 스토리지 백엔드는 단일 vCenter로 제한됩니다.  로컬에서 클러스터 자격 증명을 사용하는 경우 연관된 SVM은 자동으로 vCenter에 매핑되어 vVols 또는 VMFS를 관리합니다.  SRA를 포함한 VMFS 관리의 경우 ONTAP 도구는 글로벌 클러스터가 필요 없이 SVM 자격 증명을 지원합니다.

[role="tabbed-block"]
====
.ONTAP 도구 관리자 사용
--

NOTE: 멀티 테넌트 설정에서는 스토리지 백엔드 클러스터를 전역적으로 추가하고 SVM을 로컬로 추가하여 SVM 사용자 자격 증명을 사용할 수 있습니다.

.단계
. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 배포 중에 제공한 ONTAP tools for VMware vSphere 로 로그인합니다.
. 사이드바에서 *스토리지 백엔드*를 선택합니다.
. 스토리지 백엔드를 추가하고 서버 IP 주소 또는 FQDN, 사용자 이름 및 비밀번호 세부 정보를 제공합니다.
+

NOTE: IPv4 및 IPv6 주소 관리 LIF가 지원됩니다.



--
.vSphere 클라이언트 사용자 인터페이스 사용
--

NOTE: vSphere 클라이언트 사용자 인터페이스를 통해 스토리지 백엔드를 구성하는 경우 vVols 데이터스토어는 SVM 사용자를 직접 추가하는 것을 지원하지 않는다는 점에 유의하는 것이 중요합니다.

. vSphere 클라이언트에 로그인합니다.
. 바로가기 페이지에서 플러그인 섹션 아래에 있는 * NetApp ONTAP 도구*를 선택합니다.
. 사이드바에서 *스토리지 백엔드*를 선택합니다.
. 스토리지 백엔드를 추가하고 서버 IP 주소, 사용자 이름, 비밀번호, 포트 세부 정보를 제공합니다.
+

NOTE: SVM 사용자를 직접 추가하려면 클러스터 기반 자격 증명과 IPv4 및 IPv6 주소 관리 LIF를 추가하거나 SVM 관리 LIF와 함께 SVM 기반 자격 증명을 제공할 수 있습니다.



.다음은 무엇인가요?
목록이 새로 고쳐지고, 목록에서 새로 추가된 스토리지 백엔드를 볼 수 있습니다.

--
====