---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'ONTAP tools for VMware vSphere 사용하여 VMware vStorage API for Array Integration(VAAI)용 NetApp NFS 플러그인을 설치할 수 있습니다.' 
---
= NFS VAAI 플러그인을 설치하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS vStorage API for Array Integration(NFS VAAI) 플러그인은 VMware vSphere와 NFS 스토리지 어레이를 통합하는 소프트웨어 구성 요소입니다.  ONTAP tools for VMware vSphere 사용하여 NFS VAAI 플러그인을 설치하면 NFS 스토리지 어레이의 고급 기능을 활용하여 ESXi 호스트에서 스토리지 어레이 자체로 특정 스토리지 관련 작업을 오프로드할 수 있습니다.

.시작하기 전에
* 다운로드 https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["VMware VAAI용 NetApp NFS 플러그인"] 설치 패키지.
* ESXi 호스트와 vSphere 7.0U3 최신 패치 이상 버전, ONTAP 9.14.1 이상 버전이 있는지 확인하세요.
* NFS 데이터 저장소를 마운트합니다.


.단계
. vSphere 클라이언트에 로그인합니다.
. 플러그인 섹션에서 *바로가기* > * NetApp ONTAP 도구*를 선택합니다.
. *설정* > *NFS VAAI 도구*를 선택합니다.
. VAAI 플러그인이 vCenter Server에 업로드되면 *기존 버전* 섹션에서 *변경*을 선택합니다.  VAAI 플러그인이 vCenter Server에 업로드되지 않은 경우 *업로드* 버튼을 선택합니다.
. 탐색하고 선택하세요 `.vib` 파일을 선택하고 *업로드*를 선택하여 ONTAP 도구에 파일을 업로드합니다.
. *ESXI 호스트에 설치*를 선택하고, NFS VAAI 플러그인을 설치할 ESXi 호스트를 선택한 다음, *설치*를 선택합니다.
+
플러그인 설치에 적합한 ESXi 호스트만 표시됩니다.  vSphere Web Client의 최근 작업 섹션에서 설치 진행 상황을 모니터링할 수 있습니다.

. 설치 후 ESXi 호스트를 수동으로 다시 시작합니다.
+
VMware 관리자가 ESXi 호스트를 다시 시작하면 ONTAP tools for VMware vSphere NFS VAAI 플러그인을 자동으로 감지하고 활성화합니다.



.다음은 무엇인가요?
NFS VAAI 플러그인을 설치하고 ESXi 호스트를 재부팅한 후 VAAI 복사 오프로드에 대한 올바른 NFS 내보내기 정책을 구성해야 합니다.  NFS 환경에서 VAAI를 구성할 때 다음 요구 사항을 염두에 두고 내보내기 정책 규칙을 구성하세요.

* 해당 ONTAP 볼륨은 NFSv4 호출을 허용해야 합니다.
* 루트 사용자는 루트로 유지되어야 하며 모든 접합 부모 볼륨에서 NFSv4가 허용되어야 합니다.
* VAAI 지원 옵션은 해당 NFS 서버에서 설정해야 합니다.


절차에 대한 자세한 내용은 다음을 참조하세요. https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["VAAI 복사 오프로드를 위한 올바른 NFS 내보내기 정책 구성"] KB 문서.

.관련 정보
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["NFS를 통한 VMware vStorage 지원"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["NFSv4.0 활성화 또는 비활성화"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["NFSv4.2에 대한 ONTAP 지원"]
