---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: ONTAP tools for VMware vSphere 호스트 클러스터의 보호를 관리합니다. 
---
= 호스트 클러스터 보호를 사용하여 보호
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 호스트 클러스터의 보호를 관리합니다.  선택된 SVM에 속하고 클러스터의 하나 이상의 호스트에 마운트된 모든 데이터 저장소는 호스트 클러스터에서 보호됩니다.

.시작하기 전에
다음 전제 조건이 충족되는지 확인하세요.

* 호스트 클러스터에는 하나의 SVM에서만 데이터 저장소가 있습니다.
* 호스트 클러스터에 마운트된 데이터스토어는 클러스터 외부의 호스트에 마운트되어서는 안 됩니다.
* 호스트 클러스터에 마운트된 모든 데이터스토어는 iSCSI/FC 프로토콜을 사용하는 VMFS 데이터스토어여야 합니다. NVMe/FC 및 NVMe/TCP 프로토콜을 사용하는 vVols, NFS 또는 VMFS 데이터스토어는 지원되지 않습니다.
* 호스트 클러스터에 마운트된 FlexVol/LUN 형성 데이터 저장소는 기존 일관성 그룹(CG)의 일부가 되어서는 안 됩니다.
* 호스트 클러스터에 마운트된 FlexVol/LUN 형성 데이터 저장소는 기존 SnapMirror 관계에 포함되어서는 안 됩니다.
* 호스트 클러스터에는 최소한 하나의 데이터 저장소가 있어야 합니다.


.단계
. vSphere 클라이언트에 로그인합니다.
. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP 도구* > *클러스터 보호*를 선택합니다.
. 클러스터 보호 창에서 데이터 저장소 유형과 소스 저장소 가상 머신(VM) 세부 정보가 자동으로 채워집니다. 보호된 데이터 저장소를 보려면 데이터 저장소 링크를 선택하세요.
. *일관성 그룹 이름*을 입력하세요.
. *관계 추가*를 선택하세요.
. * SnapMirror 관계 추가* 창에서 *대상 스토리지 VM*과 *정책* 유형을 선택합니다.
+
정책 유형은 비동기 또는 AutomatedFailOverDuplex가 될 수 있습니다.

+
SnapMirror 관계를 AutomatedFailOverDuplex 유형 정책으로 추가하는 경우 ONTAP tools for VMware vSphere 배포된 동일한 vCenter에 대상 스토리지 VM을 스토리지 백엔드로 추가해야 합니다.

+
AutomatedFailOverDuplex 정책 유형에는 균일한 호스트 구성과 비균일한 호스트 구성이 있습니다. *균일한 호스트 구성* 토글 버튼을 선택하면 호스트 이니시에이터 그룹 구성이 대상 사이트에 암묵적으로 복제됩니다. 자세한 내용은 다음을 참조하세요.link:../concepts/ontap-tools-concepts-terms.html["주요 개념 및 용어"] .

. 균일하지 않은 호스트 구성을 선택하는 경우 해당 클러스터 내의 각 호스트에 대한 호스트 액세스(소스/대상)를 선택합니다.
. *추가*를 선택하세요.
. *클러스터 보호* 창에서 생성 작업 중에는 보호된 클러스터를 편집할 수 없습니다.  보호 기능을 삭제하고 다시 추가할 수 있습니다.  호스트 클러스터 보호 수정 작업 중에 편집 옵션을 사용할 수 있습니다. 줄임표 메뉴 옵션을 사용하여 관계를 편집하거나 삭제할 수 있습니다.
. *보호* 버튼을 선택하세요.
+
vCenter 작업은 작업 ID 세부 정보와 함께 생성되고, 진행 상황은 최근 작업 패널에 표시됩니다.  이는 비동기 작업입니다. 사용자 인터페이스에는 요청 제출 상태만 표시되고 작업이 완료될 때까지 기다리지 않습니다.

. 보호된 호스트 클러스터를 보려면 * NetApp ONTAP 도구* > *보호* > *호스트 클러스터 관계*로 이동합니다.

