---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphere 의 단일 인스턴스는 여러 vCenter Server 인스턴스를 관리할 수 있습니다.  ONTAP tools for VMware vSphere VASA Provider에 대한 자체 서명 인증서와 함께 배포됩니다.  이를 통해 vVols 데이터스토어에 대해 단 하나의 vCenter Server 인스턴스만 관리할 수 있습니다. 
---
= 인증서 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
배포 중에 ONTAP 도구와 VASA 공급자에 대한 자체 서명 인증서가 기본적으로 생성됩니다.  ONTAP 도구 관리자 인터페이스를 사용하면 인증서를 갱신하거나 사용자 정의 CA로 업그레이드할 수 있습니다.  다중 vCenter 배포에서는 사용자 지정 CA 인증서가 필수입니다.

.시작하기 전에
* 인증서가 발급된 도메인 이름은 가상 IP 주소에 매핑되어야 합니다.
* 도메인 이름에 대해 nslookup 검사를 실행하여 도메인이 의도한 IP 주소로 확인되는지 확인합니다.
* 인증서는 도메인 이름과 ONTAP 도구 IP 주소로 생성해야 합니다.



NOTE: ONTAP 도구 IP 주소는 정규화된 도메인 이름(FQDN)에 매핑되어야 합니다.  인증서에는 주체 또는 주체 대체 이름에 ONTAP 도구 IP 주소에 매핑된 동일한 FQDN이 포함되어야 합니다.


NOTE: CA 서명 인증서에서 자체 서명 인증서로 전환할 수 없습니다.

[role="tabbed-block"]
====
.ONTAP 도구 인증서 업그레이드
--
ONTAP 도구 탭에는 인증서 유형(자체 서명/CA 서명) 및 도메인 이름과 같은 세부 정보가 표시됩니다.  배포하는 동안 기본적으로 자체 서명된 인증서가 생성됩니다.  인증서를 갱신하거나 CA로 업그레이드할 수 있습니다.

.단계
. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 배포 중에 제공한 ONTAP tools for VMware vSphere 로 로그인합니다.
. *인증서* > * ONTAP 도구* > *갱신*을 선택하여 인증서를 갱신합니다.
+
인증서가 만료되었거나 만료일이 다가오는 경우 인증서를 갱신할 수 있습니다.  인증서 유형이 CA 서명인 경우 갱신 옵션을 사용할 수 있습니다.  팝업 창에서 서버 인증서, 개인 키, 루트 CA 및 중간 인증서 세부 정보를 제공합니다.

+

NOTE: 인증서가 갱신될 때까지 시스템은 오프라인 상태가 되며, ONTAP 도구 관리자 인터페이스에서 로그아웃됩니다.

. 자체 서명된 인증서를 사용자 지정 CA 인증서로 업그레이드하려면 *인증서* > * ONTAP 도구* > *CA로 업그레이드* 옵션을 선택합니다.
+
.. 팝업 창에서 서버 인증서, 서버 인증서 개인 키, 루트 CA 인증서, 중간 인증서 파일을 업로드합니다.
.. 이 인증서를 생성한 도메인 이름을 입력하고 인증서를 업그레이드하세요.
+

NOTE: 업그레이드가 완료될 때까지 시스템은 오프라인 상태가 되며, ONTAP 도구 관리자 인터페이스에서 로그아웃됩니다.





--
.VASA 공급자 인증서 업그레이드
--
ONTAP tools for VMware vSphere VASA Provider에 대한 자체 서명 인증서와 함께 배포됩니다.  이를 통해 vVols 데이터스토어에 대해 단 하나의 vCenter Server 인스턴스만 관리할 수 있습니다.  여러 vCenter Server 인스턴스를 관리하고 해당 인스턴스에서 vVols 기능을 활성화하려면 자체 서명된 인증서를 사용자 지정 CA 인증서로 변경해야 합니다.

.단계
. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 배포 중에 제공한 ONTAP tools for VMware vSphere 로 로그인합니다.
. *인증서* > *VASA 공급자* 또는 * ONTAP 도구* > *갱신*을 선택하여 인증서를 갱신합니다.
. *인증서* > *VASA 공급자* 또는 * ONTAP 도구* > *CA로 업그레이드*를 선택하여 자체 서명 인증서를 사용자 지정 CA 인증서로 업그레이드합니다.
+
.. 팝업 창에서 서버 인증서, 서버 인증서 개인 키, 루트 CA 인증서, 중간 인증서 파일을 업로드합니다.
.. 이 인증서를 생성한 도메인 이름을 입력하고 인증서를 업그레이드하세요.
+

NOTE: 업그레이드가 완료될 때까지 시스템은 오프라인 상태가 되며, ONTAP 도구 관리자 인터페이스에서 로그아웃됩니다.





--
====