---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 데이터 저장소 삭제 작업은 데이터 저장소를 삭제합니다.  NFS 또는 VMFS 데이터 저장소의 경우 데이터 저장소를 사용 중인 VM 목록이 있는 대화 상자가 나타납니다. 
---
= 데이터 저장소 삭제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 저장소에서 저장소 제거 작업은 vCenter Server에서 VMware vSphere가 검색하거나 관리하는 vVols 데이터 저장소에 ONTAP tools for VMware vSphere 에서 지원됩니다.  이 작업을 수행하면 vVols 데이터 저장소에서 볼륨을 제거할 수 있습니다.

특정 볼륨에 vVols 있는 경우 제거 옵션이 비활성화됩니다.  데이터 저장소에서 볼륨을 제거하는 것 외에도 ONTAP 스토리지에서 선택한 볼륨을 삭제할 수 있습니다.

vCenter Server의 ONTAP tools for VMware vSphere 에서 데이터 저장소 삭제 작업은 다음을 수행합니다.

* vVol 컨테이너를 마운트 해제합니다.
* igroup을 정리합니다.  igroup을 사용하지 않으면 igroup에서 iqn을 제거합니다.
* Vvol 컨테이너를 삭제합니다.
* Flex 볼륨을 스토리지 어레이에 그대로 둡니다.


vCenter Server의 ONTAP 도구에서 NFS, VMFS 또는 vVOL 데이터스토어를 삭제하려면 아래 단계를 따르세요.

.단계
. vSphere 클라이언트에 로그인합니다.
. 호스트 시스템이나 호스트 클러스터 또는 데이터 센터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP 도구* > *데이터 저장소 삭제*를 선택합니다.
+

NOTE: 해당 데이터스토어를 사용하는 가상 머신이 있는 경우 해당 데이터스토어를 삭제할 수 없습니다.  데이터 저장소를 삭제하기 전에 가상 머신을 다른 데이터 저장소로 옮겨야 합니다.  데이터 저장소가 보호된 호스트 클러스터에 속하는 경우 볼륨 삭제 확인란을 선택할 수 없습니다.

+
.. NFS 또는 VMFS 데이터 저장소의 경우 데이터 저장소를 사용 중인 VM 목록이 있는 대화 상자가 나타납니다.
.. VMFS 데이터 저장소가 ASA r2 시스템에 생성되었고 보호의 일부인 경우, 데이터 저장소를 삭제하기 전에 보호를 해제해야 합니다.
.. vVols 데이터 저장소의 경우, 데이터 저장소 삭제 작업은 연관된 vVols 없을 때만 데이터 저장소를 삭제합니다.  데이터 저장소 삭제 대화 상자는 ONTAP 클러스터에서 볼륨을 삭제하는 옵션을 제공합니다.
.. ASA r2 시스템 기반 vVols 데이터 저장소의 경우 백업 볼륨을 삭제하는 체크박스는 적용되지 않습니다.


. ONTAP 스토리지의 백업 볼륨을 삭제하려면 * ONTAP 클러스터의 볼륨 삭제*를 선택합니다.
+

NOTE: 보호된 호스트 클러스터의 일부인 VMFS 데이터 저장소에 대한 ONTAP 클러스터의 볼륨을 삭제할 수 없습니다.


