---
permalink: manage/enable-backup.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphere 부터 어플라이언스는 동적 스토리지 프로비저너를 사용하므로 RPO를 0으로 설정할 수 없습니다.  하지만 RPO를 거의 0에 가깝게 달성할 수도 있습니다. 
---
= 백업을 생성하고 ONTAP 도구 설정을 복구합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 부터 어플라이언스는 동적 스토리지 프로비저너를 사용하므로 제로 RPO를 달성할 수 없습니다.  하지만 RPO를 거의 0에 가깝게 달성할 수도 있습니다.  거의 0에 가까운 RPO를 달성하려면 설정 백업을 만들고 새 가상 머신에 복원해야 합니다.


NOTE: 비HA 백업이 활성화된 경우 HA로 마이그레이션하려면 먼저 백업을 비활성화한 다음 마이그레이션 후 다시 활성화하세요.



== 백업을 생성하고 백업 파일을 다운로드합니다.

.단계
. vCenter Server에서 유지 관리 콘솔을 엽니다.
. 유지 관리 사용자로 로그인합니다.
. 입력하다 `4` *지원 및 진단*을 선택하세요.
. 입력하다 `3` *시스템 백업 활성화* 옵션을 선택하세요.
. HA가 아닌 경우 ONTAP 도구 가상 머신이 배포된 vCenter 자격 증명을 입력합니다.
. 백업 빈도 값을 5분에서 60분 사이로 입력하세요.
. *Enter*를 누르세요
+
이렇게 하면 백업이 생성되고 정기적으로 가상 머신의 데이터 저장소에 백업이 푸시됩니다.

. 백업에 액세스하려면 저장소 섹션으로 이동하여 가상 머신의 데이터 저장소를 선택하세요.
. *파일* 섹션을 선택하세요.
+
파일 섹션에서 디렉토리를 볼 수 있습니다.  디렉토리 이름은 ONTAP 도구 IP 주소가 되며, 여기서 점(.)은 밑줄로 바뀌고 _backup_이 접미사로 붙습니다.

. 백업에 대한 자세한 내용을 보려면 *파일* > *다운로드*에서 backup_info.txt 파일을 다운로드하세요.




== 다시 덮다

설정을 복구하려면 기존 가상 머신의 전원을 끄고 초기 배포에 사용된 OVA를 사용하여 새 가상 머신을 배포합니다.

새 가상 머신에 동일한 ONTAP 도구 IP 주소를 사용해야 하며, 서비스 활성화, 노드 크기, HA 모드 등의 시스템 구성은 초기 배포와 동일해야 합니다.

백업 파일에서 설치 프로그램을 복구하려면 다음 단계를 수행하세요.

. vCenter Server에서 유지 관리 콘솔을 엽니다.
. 유지 관리 사용자로 로그인합니다.
. 입력하다 `4` *지원 및 진단*을 선택하세요.
. 입력하다 `2` *원격 진단 액세스 활성화* 옵션을 선택하고 진단 액세스에 대한 새 비밀번호를 만듭니다.
. 다운로드한 디렉토리에서 백업 하나를 선택하세요.  최신 백업 파일 이름은 _backup_info.txt_ 파일에 기록됩니다.
. 아래 명령을 실행하여 백업을 새 가상 머신에 복사하고 메시지가 표시되면 진단 암호를 입력합니다.
+
[listing]
----
scp <Backup_X.tar.enc> diag@<node_ip>:/home/diag/system_recovery.tar.enc
----
+

NOTE: 명령에 언급된 대상 경로와 파일 이름(/home/diag/system_recovery.tar.enc)을 변경하지 마세요.

. 백업 파일을 복사한 후 진단 셸에 로그인하여 다음 명령을 실행합니다.
+
[listing]
----
sudo perl /home/maint/scripts/post-deploy-upgrade.pl -recovery
----
+
로그는 _/var/log/post-deploy-upgrade.log_ 파일에 기록됩니다.

. 성공적으로 복구되면 서비스와 vCenter 개체가 복원됩니다.

