---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: 데이터 센터에서 기존 가상 머신을 마이그레이션할 때는 몇 가지 고려 사항을 알아야 합니다. 
---
= 가상 머신을 마이그레이션하거나 복제할 때의 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 센터에서 기존 가상 머신을 마이그레이션할 때는 몇 가지 고려 사항을 알아야 합니다.



== 보호된 가상 머신 마이그레이션

보호된 가상 머신을 다음으로 마이그레이션할 수 있습니다.

* 다른 ESXi 호스트의 동일한 vVols 데이터 저장소
* 동일한 ESXi 호스트에 서로 다른 호환 vVols 데이터 저장소가 있음
* 다른 ESXi 호스트의 서로 다른 호환 vVols 데이터 저장소


가상 머신이 다른 FlexVol volume 으로 마이그레이션되면 해당 메타데이터 파일도 가상 머신 정보로 업데이트됩니다.  가상 머신이 동일한 스토리지를 사용하지만 다른 ESXi 호스트로 마이그레이션되는 경우 기본 FlexVol volume 메타데이터 파일은 수정되지 않습니다.



== 보호된 가상 머신 복제

보호된 가상 머신을 다음으로 복제할 수 있습니다.

* 복제 그룹을 사용하는 동일한 FlexVol volume 의 동일한 컨테이너
+
동일한 FlexVol 볼륨의 메타데이터 파일이 복제된 가상 머신 세부 정보로 업데이트됩니다.

* 복제 그룹을 사용하는 다른 FlexVol volume 의 동일한 컨테이너
+
복제된 가상 머신이 배치된 FlexVol volume 메타데이터 파일은 복제된 가상 머신 세부 정보로 업데이트됩니다.

* 다른 컨테이너 또는 vVols 데이터 저장소
+
복제된 가상 머신이 배치된 FlexVol volume 메타데이터 파일은 가상 머신 세부 정보를 업데이트합니다.



VMware는 현재 VM 템플릿에 복제된 가상 머신을 지원하지 않습니다.

보호된 가상 머신의 복제본이 지원됩니다.

참조하다 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["복제를 위한 가상 머신 생성"] 자세한 내용은.



== 가상 머신 스냅샷

현재는 메모리가 없는 가상 머신 스냅샷만 지원됩니다.  가상 머신에 메모리가 포함된 스냅샷이 있는 경우 해당 가상 머신은 보호 대상으로 간주되지 않습니다.

메모리 스냅샷이 있는 보호되지 않은 가상 머신도 보호할 수 없습니다. 이 릴리스에서는 가상 머신에 대한 보호를 활성화하기 전에 메모리 스냅샷을 삭제해야 합니다.

ASA r2 스토리지 유형을 사용하는 Windows VM의 경우 가상 머신의 스냅샷을 찍으면 읽기 전용 스냅샷이 됩니다.  VM에 대한 전원 공급 요청이 있을 때 VASA 공급자는 읽기 전용 스냅샷을 사용하여 LUN을 생성한 다음 IOPS를 활성화합니다.  전원 끄기 요청 중에 VASA 공급자는 생성된 LUN을 삭제한 다음 IOPS를 비활성화합니다.
