---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 백엔드는 ESXi 호스트가 데이터를 저장하는 데 사용하는 시스템입니다. 
---
= 스토리지 백엔드 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 백엔드는 ESXi 호스트가 데이터를 저장하는 데 사용하는 시스템입니다.



== 스토리지를 발견하세요

예약된 검색으로 스토리지 세부 정보가 업데이트될 때까지 기다리지 않고도 필요에 따라 스토리지 백엔드 검색을 실행할 수 있습니다.

아래 단계에 따라 스토리지 백엔드를 찾아보세요.

.단계
. vSphere 클라이언트에 로그인합니다.
. 바로가기 페이지에서 플러그인 섹션 아래에 있는 * NetApp ONTAP 도구*를 선택합니다.
. ONTAP 도구의 왼쪽 창에서 *스토리지 백엔드*로 이동하여 스토리지 백엔드를 선택합니다.
. 세로 줄임표 메뉴를 선택하고 *저장소 검색*을 선택하세요.


최근 작업 패널에서 진행 상황을 추적할 수 있습니다.



== 스토리지 백엔드 수정

이 섹션의 단계에 따라 스토리지 백엔드를 수정하세요.

. vSphere 클라이언트에 로그인합니다.
. 바로가기 페이지에서 플러그인 섹션 아래에 있는 * NetApp ONTAP 도구*를 선택합니다.
. ONTAP 도구의 왼쪽 창에서 *스토리지 백엔드*로 이동하여 스토리지 백엔드를 선택합니다.
. 수직 타원 메뉴를 선택하고 *수정*을 선택하여 자격 증명이나 포트 이름을 수정합니다. 최근 작업 패널에서 진행 상황을 추적할 수 있습니다.


다음 단계에 따라 ONTAP 도구 관리자를 사용하여 글로벌 ONTAP 클러스터에 대한 수정 작업을 수행할 수 있습니다.

. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 배포 중에 제공한 ONTAP tools for VMware vSphere 로 로그인합니다.
. 사이드바에서 스토리지 백엔드를 선택하세요.
. 수정하려는 스토리지 백엔드를 선택하세요.
. 세로 줄임표 메뉴를 선택하고 *수정*을 선택합니다.
. 자격 증명이나 포트를 수정할 수 있습니다.  스토리지 백엔드를 수정하려면 *사용자 이름*과 *비밀번호*를 입력하세요.




== 스토리지 백엔드 제거

스토리지 백엔드를 제거하기 전에 스토리지 백엔드에 연결된 모든 데이터스토어를 삭제해야 합니다. 스토리지 백엔드를 제거하려면 아래 단계를 따르세요.

. vSphere 클라이언트에 로그인합니다.
. 바로가기 페이지에서 플러그인 섹션 아래에 있는 * NetApp ONTAP 도구*를 선택합니다.
. ONTAP 도구의 왼쪽 창에서 *스토리지 백엔드*로 이동하여 스토리지 백엔드를 선택합니다.
. 세로 줄임표 메뉴를 선택하고 *제거*를 선택합니다. 스토리지 백엔드에 데이터스토어가 포함되어 있지 않은지 확인하세요. 최근 작업 패널에서 진행 상황을 추적할 수 있습니다.


ONTAP 도구 관리자를 사용하여 글로벌 ONTAP 클러스터에 대한 제거 작업을 수행할 수 있습니다.

. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 배포 중에 제공한 ONTAP tools for VMware vSphere 로 로그인합니다.
. 사이드바에서 *스토리지 백엔드*를 선택합니다.
. 제거할 스토리지 백엔드를 선택하세요
. 세로 줄임표 메뉴를 선택하고 *제거*를 선택합니다.




== 스토리지 백엔드의 드릴다운 보기

스토리지 백엔드 페이지에는 모든 스토리지 백엔드가 나열되어 있습니다. 클러스터 아래의 개별 자식 SVM이 아닌, 추가한 스토리지 백엔드에서 스토리지 검색, 수정 및 제거 작업을 수행할 수 있습니다.

스토리지 백엔드에서 부모 클러스터나 자식 클러스터를 선택하면 해당 구성 요소의 전반적인 요약을 볼 수 있습니다.  부모 클러스터를 선택하면 저장소 검색, 수정, 제거 작업을 수행할 수 있는 작업 드롭다운이 표시됩니다.

요약 페이지에는 다음과 같은 세부 정보가 제공됩니다.

* 스토리지 백엔드의 상태
* 용량 정보
* VM에 대한 기본 정보
* IP 주소, 네트워크 포트와 같은 네트워크 정보입니다. 자식 SVM의 경우 정보는 부모 스토리지 백엔드와 동일합니다.
* 저장소 백엔드에 허용되고 제한되는 Privileges . 자식 SVM의 경우 정보는 부모 스토리지 백엔드와 동일합니다.  Privileges 클러스터 기반 스토리지 백엔드에만 표시됩니다.  SVM을 스토리지 백엔드로 추가하면 권한 정보가 표시되지 않습니다.
* SVM 또는 클러스터에 대해 분리 속성이 "true"로 설정된 경우 ASA r2 시스템 클러스터 드릴다운 보기에는 로컬 계층 탭이 포함되지 않습니다.
* ASA r2 SVM 시스템의 경우 용량 포틀릿이 표시되지 않습니다.  용량 포털은 SVM 또는 클러스터에 대해 분리 속성이 "true"로 설정된 경우에만 필요합니다.
* ASA r2 SVM 시스템의 경우 기본 정보 섹션에 플랫폼 유형이 표시됩니다.


인터페이스 탭은 인터페이스에 대한 자세한 정보를 제공합니다.

로컬 티어 탭은 집계 목록에 대한 자세한 정보를 제공합니다.
